<script setup>
import { computed, ref } from 'vue'
const props = defineProps({ organizations: { type:Array, default:() => [] }, applications: { type:Array, default:() => [] }, loading:Boolean })
const emit = defineEmits(['apply','refresh'])
const activeTab = ref('organizations')
const safeOrganizations = computed(() => Array.isArray(props.organizations) ? props.organizations : [])
const safeApplications = computed(() => Array.isArray(props.applications) ? props.applications : [])
const applicationByOrganization = computed(() => new Map(safeApplications.value.map((item) => [item.organization_id,item])))
function applicationLabel(id) { const status=applicationByOrganization.value.get(id)?.status; return ({pending:'审核中',approved:'已批准',rejected:'已拒绝，可重新申请'})[status] || '申请加入' }
function canApply(id) { const status=applicationByOrganization.value.get(id)?.status; return !props.loading && status !== 'pending' && status !== 'approved' }
</script>

<template>
  <section class="page-stack"><article class="panel"><div class="application-toolbar"><div class="application-tabs" role="tablist"><button :class="{active:activeTab === 'organizations'}" type="button" @click="activeTab='organizations'">可申请组织 <span>{{ safeOrganizations.length }}</span></button><button :class="{active:activeTab === 'applications'}" type="button" @click="activeTab='applications'">我的申请 <span>{{ safeApplications.length }}</span></button></div><button class="text-button" type="button" @click="emit('refresh')">刷新</button></div><div v-if="activeTab === 'organizations'" class="tab-panel"><ul class="item-list"><li v-for="organization in safeOrganizations" :key="organization.ID"><div><strong>{{ organization.name }}</strong><small>{{ organization.code }} · {{ organization.parent_id ? '下级组织' : '一级组织' }}</small></div><button type="button" :disabled="!canApply(organization.ID)" @click="emit('apply', organization.ID)">{{ applicationLabel(organization.ID) }}</button></li><li v-if="!safeOrganizations.length" class="muted">当前没有可申请的公开组织。</li></ul></div><div v-else class="tab-panel"><ul class="item-list"><li v-for="application in safeApplications" :key="application.id"><div><strong>{{ application.organization_name }}</strong><small>提交于 {{ new Date(application.created_at).toLocaleString() }}</small></div><span :class="['status',application.status]">{{ ({pending:'审核中',approved:'已批准',rejected:'已拒绝'})[application.status] || application.status }}</span></li><li v-if="!safeApplications.length" class="muted">还没有提交组织申请。</li></ul></div></article></section>
</template>

<style scoped>
.page-stack{display:grid;gap:20px}.panel{padding:26px;border:1px solid #dce5df;border-radius:12px;background:#fff;box-shadow:0 10px 28px rgba(30,58,44,.05)}.text-button,.application-tabs button,.item-list button{font:inherit;cursor:pointer}.text-button{border:0;color:#1b6854;background:none;font-weight:700}.application-toolbar{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:18px}.application-tabs{display:flex;align-items:center;gap:8px}.application-tabs button{display:inline-flex;min-height:40px;align-items:center;gap:8px;padding:0 14px;border:1px solid #d8e4dc;border-radius:8px;color:#60746a;background:#fff;font-size:13px;font-weight:700}.application-tabs button:hover{border-color:#aacbb8;color:#24654f;background:#f4faf6}.application-tabs button.active{border-color:#1e6956;color:#fff;background:#1e6956;box-shadow:0 1px 2px rgba(17,78,57,.18)}.application-tabs span{display:inline-grid;min-width:22px;height:22px;place-items:center;padding:0 6px;border-radius:999px;color:#5a7769;background:#e5ede7;font-size:11px}.application-tabs button.active span{color:#1e6956;background:#fff}.tab-panel{min-height:320px}.item-list{display:grid;gap:8px;margin:0;padding:0;list-style:none}.item-list li{display:flex;align-items:center;gap:14px;padding:15px 14px;border:1px solid #e6eee8;border-radius:9px;background:#fbfdfb}.item-list strong,.item-list small{display:block}.item-list small,.muted{margin-top:4px;color:#76877e;font-size:12px}.item-list button{margin-left:auto;min-height:36px;padding:0 12px;border:0;border-radius:7px;color:#fff;background:#1e6956;font-weight:700}.item-list button:disabled{color:#74837b;background:#e6ece7}.status{margin-left:auto;padding:5px 9px;border-radius:999px;font-size:12px;font-weight:700}.status.pending{color:#8a6200;background:#fff4cf}.status.approved{color:#28614c;background:#e6f3e9}.status.rejected{color:#923d35;background:#fce9e6}.muted{display:block;justify-content:center;min-height:180px;padding:55px 0;border:0!important;text-align:center}@media(max-width:600px){.panel{padding:20px}.application-toolbar{align-items:stretch;flex-direction:column}.application-toolbar>.text-button{align-self:flex-end}.application-tabs{width:100%}.application-tabs button{flex:1;justify-content:center}.item-list li{align-items:flex-start;flex-wrap:wrap}.item-list button,.status{margin-left:auto}}
</style>
