<script setup>
import { computed, ref } from 'vue'
const props = defineProps({ applications: { type: Array, default: () => [] }, loading: Boolean })
const emit = defineEmits(['review', 'refresh'])
const activeTab = ref('pending')
const pending = computed(() => (Array.isArray(props.applications) ? props.applications : []).filter((item) => item.status === 'pending'))
const history = computed(() => (Array.isArray(props.applications) ? props.applications : []).filter((item) => item.status !== 'pending'))
</script>

<template>
  <section class="review-page"><article class="panel"><div class="review-toolbar"><div class="review-tabs"><button :class="{ active: activeTab === 'pending' }" type="button" @click="activeTab = 'pending'">待审核申请 <span>{{ pending.length }}</span></button><button :class="{ active: activeTab === 'history' }" type="button" @click="activeTab = 'history'">已处理申请 <span>{{ history.length }}</span></button></div><button class="text-button" type="button" @click="emit('refresh')">刷新</button></div><div v-if="activeTab === 'pending'" class="tab-panel"><div v-if="!pending.length" class="empty"><strong>当前没有待审核申请</strong><span>新的工作空间加入申请会显示在这里。</span></div><div v-for="application in pending" :key="application.id" class="review-row"><div><strong>{{ application.username }}</strong><small>提交于 {{ new Date(application.created_at).toLocaleString() }}</small></div><span class="default-role">批准后授予工作空间默认角色</span><div class="actions"><button class="approve" :disabled="loading" type="button" @click="emit('review', { id: application.id, approve: true })">批准</button><button class="reject" :disabled="loading" type="button" @click="emit('review', { id: application.id, approve: false })">拒绝</button></div></div></div><div v-else class="tab-panel"><ul class="history"><li v-for="application in history" :key="application.id"><span><strong>{{ application.username }}</strong><small>{{ new Date(application.created_at).toLocaleString() }}</small></span><em :class="application.status">{{ application.status === 'approved' ? '已批准' : '已拒绝' }}</em></li><li v-if="!history.length" class="muted">暂无已处理记录。</li></ul></div></article></section>
</template>

<style scoped>
.review-page{display:grid}.panel{padding:26px;border:1px solid #dce5df;border-radius:12px;background:#fff;box-shadow:0 10px 28px rgba(30,58,44,.05)}.review-toolbar{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:20px}.review-tabs{display:flex;gap:8px}.review-tabs button,.text-button,.actions button{font:inherit;cursor:pointer}.review-tabs button{display:inline-flex;min-height:40px;align-items:center;gap:8px;padding:0 14px;border:1px solid #c9dcd0;border-radius:8px;color:#486559;background:#f8fbf8;font-weight:700}.review-tabs button.active{border-color:#1e6956;color:#fff;background:#1e6956}.review-tabs span{display:inline-grid;min-width:22px;height:22px;place-items:center;padding:0 6px;border-radius:999px;color:#2d7055;background:#e5f3e8;font-size:11px}.review-tabs button.active span{color:#1e6956;background:#fff}.text-button{border:0;color:#1b6854;background:none;font-weight:700}.tab-panel{min-height:300px}.empty{display:grid;place-items:center;gap:8px;min-height:300px;color:#72847a;text-align:center}.empty strong{color:#2d5d4b;font-size:18px}.review-row{display:grid;grid-template-columns:minmax(180px,1fr) minmax(160px,240px) auto;gap:14px;align-items:center;padding:15px 0;border-bottom:1px solid #edf1ee}.review-row strong,.review-row small{display:block}.review-row small,.muted{margin-top:4px;color:#76877e;font-size:12px}.default-role{padding:7px 10px;border-radius:7px;color:#48685a;background:#edf5ef;font-size:12px}.actions{display:flex;gap:8px}.actions button{min-width:68px;min-height:38px;border:0;border-radius:7px;color:#fff;font-weight:700}.actions button:disabled{opacity:.6;cursor:wait}.approve{background:#1e6956}.reject{background:#974c45}.history{display:grid;gap:6px;margin:0;padding:0;list-style:none}.history li{display:flex;align-items:center;justify-content:space-between;min-height:60px;padding:12px 0;border-bottom:1px solid #edf1ee}.history strong,.history small{display:block}.history small{margin-top:3px;color:#76877e;font-size:12px}.history em{padding:4px 8px;border-radius:999px;font-size:12px;font-style:normal;font-weight:700}.history em.approved{color:#28614c;background:#e6f3e9}.history em.rejected{color:#913f38;background:#fbeae7}.muted{display:block;min-height:220px;padding:72px 0;text-align:center}@media(max-width:700px){.panel{padding:20px}.review-toolbar{align-items:flex-start;flex-direction:column}.review-row{grid-template-columns:1fr}.default-role{width:fit-content}}
</style>
